### ISSUE TITLE
Install from source with wrong file access rights

### ISSUE THREAD

**Issue by cornelinux** [zammad/zammad-documentation#10]
THe installation from source as described here
https://github.com/zammad/zammad-documentation/blob/master/install-source.rst
does not work out.

When unpacking the tgz as mentioned, the files belong to 501:staff!

    root@shell> useradd zammad
    root@shell> su - zammad

Then user zammad has no access to /opt/zammad !

When running 

    gem install bundler

the user zammad has no access rights to /var...

    zammad@zammad:/opt/zammad$ gem install bundler
    ERROR:  While executing gem ... (Gem::FilePermissionError)
        You don't have write permissions for the /var/lib/gems/2.3.0 directory.

It is unclear if the gems should be install systemwide (as root) or locally (as zammad). But then the access rights are not straight.

**Comment by monotek** [comment]
The generic source install doc is not about covering evry bit of the installation because this can differ depending on used os.

Nevertheless i changed the user creation command to also add the home dir in https://github.com/zammad/zammad-documentation/commit/8b416402d0e66adb1d2bb460827b778e870d98d6

I think the rest is ok. Installing the Ruby environment before installing Zammad is up to the user.

One could use RVM like described here: 

https://docs.zammad.org/en/latest/contributing-install-source.html#install-environnment

**Comment by cornelinux** [comment]
thx
