### ISSUE TITLE
zammad.conf

### ISSUE THREAD

**Issue by vxrdanny** [zammad/zammad-documentation#197]
I've tried building his numerous times now on different OS (ubuntu, centos etc), following the instructions. When I perform the copy instruction to copy the conf file, it states that the "upstream" directive is not allowed. I then comment this out and I get the same error saying "server" directive not allowed. It does this whether I edit the file or not, as soon as I copy the default file and reboot nginx, failure.  Can't get past this point as I don't know what the default conf should be.

Can someone please help me or give me a copy of their working conf file?

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
