### ISSUE TITLE
Missing documentation of roles API endpoint

### ISSUE THREAD

**Issue by bogatkaj** [zammad/zammad-documentation#223]
The documentation of the roles endpoint (/api/v1/roles) of the API is completely missing.

**Comment by matmccabe** [comment]
Hello, is this something I can contribute to?

**Comment by MrGeneration** [comment]
Hey,

> is this something I can contribute to?

contributions are warmly welcome and appreciated!
You can find our current documentation style for API endpoints e.g. here:
https://docs.zammad.org/en/latest/api/user.html

Said page above is the following page source code wise:
https://github.com/zammad/zammad-documentation/blob/main/api/user.rst

**Comment by matmccabe** [comment]
@MrGeneration This looks great and the information about the /users endpoint is very helpful. Did you have additional links to the developer notes or OpenAPI spec I can review? I have been searching for a project to dive into so I will need some fast-paced onboarding/familiarization.

**Comment by MrGeneration** [comment]
Thank you for your patience.
I'm afraid there's no such thing as developer notes or similar.

When I'm documenting endpoints (like what you can already find in the docs), what I mainly to is look what a GET gives me.
On top of that I'm running some updates via UI (it uses the API as well :) ) and am viewing that via developer tools.

This should help to document what you can do and what not.

Regarding endpoints, you can generate a full list of available endpoints via `rake routes` (add `zammad run` on package installations) on any available Zammad instance.

For a current Zammad v5.1.1 endpoints containing "role" are these:
```
                                       api_v1_roles GET                         /api/v1/roles(.:format)                                                                           roles#index
                                                    GET                         /api/v1/roles/:id(.:format)                                                                       roles#show
                                                    POST                        /api/v1/roles(.:format)                                                                           roles#create
                                                    PUT                         /api/v1/roles/:id(.:format)                                                                       roles#update
```

I hope this helps.

**Comment by matmccabe** [comment]
Hi marcel, This does help alot, however, I am having trouble initiating the
program to access developer tools. I do have a strong knowledge base but I
still do remain a writer more than a dev so I may need a little more help
getting the testing environment to make requests available.

**Comment by MrGeneration** [comment]
Hey,

I am sorry. My time ressources are currently very limitted which is why I cannot provide too much help here.
To have a look on how Zammad requests data, you don't need any special environment - as Zammads UI does use API requests as well, you can simply lurk! For this any Zammad instance will do, if you don't have one and don't want hassle, you can also do this in our trial instances without issue: https://zammad.com/en/getting-started

With developer tools I mean your browsers developer tools. Usually called via STRG + SHIFT + C or F12 depending on your browser. From there you can use the network tab to see how requests were contructed:

![image](https://user-images.githubusercontent.com/6549061/168820333-2d89542b-d1c9-4864-805f-e934f9164345.png)

I hope this helps you on your journey.
