### ISSUE TITLE
Fetching `text/plain` article via the API?

### ISSUE THREAD

**Issue by dkasak** [zammad/zammad-documentation#224]
The `GET https://newvector.zammad.com/api/v1/ticket_articles/by_ticket/{ticket id}` API seems to only return `text/html` versions of the articles. How do I get `text/plain`?

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
