### ISSUE TITLE
Generic CTI API changed? 

### ISSUE THREAD

**Issue by MPeuker** [zammad/zammad-documentation#244]
I created a powershell script that act as "bridge" between our anynode SBC and ZAMMAD.
It worked until the events "newCall" / "hangup" / "answer" contained the attribute "callid" as written in the docs.

Since a few days it I received an error message like "call_id" is missing... So I changed my script from attribute "callid" to attribute "call_id" and it works again...

Maybe this happened by accident but it still differes from the documentation...

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by MPeuker** [comment]
Oh, you totally misunderstood me...
I just wanted to inform you that the documentation ist wrong...

https://github.com/zammad/zammad-documentation/blob/main/api/generic-cti/newcall-event.rst

the attribute

callid 

is now longer "callid" but "call_id"

Technically I can handle it... :-)

**Comment by MrGeneration** [comment]
No no, you just can't read that's the issue.
There's a difference in between `callid` and `callId`.

**Comment by MPeuker** [comment]
same here
https://github.com/zammad/zammad-documentation/blob/main/api/generic-cti/answer-event.rst
and here
https://github.com/zammad/zammad-documentation/blob/main/api/generic-cti/hangup-event.rst

**Comment by MPeuker** [comment]
okay, you are right callid and callId ist not the same...

but both are wrong
call_id 
(with underbar)
works..

**Comment by MrGeneration** [comment]
Warning. Stop asking technical questions if you're not sure what you're talking about.
Other wise I'll have to ban you from this repository.

Have a look in the code and trust the documentation guy telling you twice, fairly friendly, that you're wrong.
https://github.com/zammad/zammad/blob/24c3bdfd8748874cb5f16c4e618cf78cded47743/app/models/cti/log.rb#L362

**Comment by MPeuker** [comment]
Please don't be so rude - I know understand what you mean - sorry for that.
