### ISSUE TITLE
[Feature request] OAS3 Documentation of API

### ISSUE THREAD

**Issue by bogatkaj** [zammad/zammad-documentation#269]
I'm currently working of an implementation of Zammad in a Software and am gradually really annoyed by the lack of documentation.

Would it be possible to start documanting the API in the Open API Standart 3 (OAS3) style?

This way everyone could better understand how to perform the action he or she wants.
Also everyone could visualize the API via Swagger editor (https://editor.swagger.io) or Insomnia (and similar tools).

**Comment by MrGeneration** [comment]
The style of documentation you're asking for is, as far as I understand said standard, is not supported by restructured text.
That would mean we'd have to open a fourth (!!) documentation just for the API. That's a bit much, it's difficult to maintain the already existing three especially when it comes to "where to put a piece of information".

Also, those visualizations have a downside:
Allowing you to test live on an endpoint requires an Zammad instance that actually behaves like the instance. It doesn't make any sense to have this kind of thing globally for everyone - because your instance might be unique in it's configuration.

For that reason, IF there would be such a thing, it would make much more sense in Zammad's core.

Please create a feature request on the community board for Zammad's core if you believe this is a must have:
https://community.zammad.org/c/stuff-you-like-zammad-to-have-feel-free-to-discuss-and-add-proposals/6

I'll be closing this FR as won't fix, because I believe this is the current state as mentioned above.
We have far more important construction sites documentation wise than the API - I know that's frustrating for you but that's the way it is right now. I'm basically playing one man army here.

Just a small tip at the end: Open your developer console and do what you want to do on the API in  Zammad's UI. Use the network tab to reverse engineer. It's the fastest and easiest way. Not nice but the best shot right now.
