### ISSUE TITLE
Admin - Overviews: Column LINK missing in documentation

### ISSUE THREAD

**Issue by ingokeck** [zammad/zammad-documentation#451]
If you go to Admin -> Overviews you see a list of all overviews. This list has a column "LINK". 

There is no information in the documentation what this LINK means.

**Comment by ralf401** [comment]
Thanks for your suggestion!

This is basically a read-only string which names the original overview. Because there is no function for the user/admin behind it, we didn't document it. However, all relevant fields for overviews are described, so I would close this issue (the right repo would be [here](https://github.com/zammad/zammad-admin-documentation) anyway).
