### ISSUE TITLE
Evaluate if "step 4" can be removed from update instructions (package)

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad-documentation#563]
We might be able to remove Step 4 of our update instruction for package installations:
![Image](https://github.com/user-attachments/assets/faf782a0-1eec-4bbe-abc2-c82ed7b1b3e1)

https://docs.zammad.org/en/latest/install/update.html

Because it's done here:
https://github.com/zammad/zammad/blob/develop/contrib/packager.io/functions#L363

@martini can you please confirm?

**Comment by ralf401** [comment]
Hi @YetAnotherGerrit & @martini,

I'm not sure what to do with this issue. As far as I understood, step 4 could be removed because it is done automatically in the update logic. I could not find a hint why this was added to the documentation. On the other hand, it doesn't really hurt if it is in there... 

I would tend to remove it. Any objections?

**Comment by MrGeneration** [comment]
It's a old left over.
