### ISSUE TITLE
Swagger / OpenAPI definition

### ISSUE THREAD

**Issue by mattronix** [zammad/zammad-documentation#74]
Hello Zammad,

Just wanted to ask a question about Swagger API definition of Zammad, would it be possible to get a swagger definition of the entire API's supported methods, this would allow people to test against it a bit better and to put API management software in-front of it.

Thank you very much! 

Amazing work on zammad its really awesome!

**Comment by thorsteneckel** [comment]
Hi @mattronix - thanks for reaching out! We once evaluated the usage of Swagger / OpenAPI but had to realize that it comes with a huge initial effort in creating the definition and keeping it in sync. Other from that Zammad is pretty generic (because of the ObjectManager::Attributes). When we evaluated Swagger / OpenAPI there was no way to reflect that. So in the end we decided against the integration. I can't forecast the future but for now we have no plans to provide a documentation on that level yet. Probably with v2 of the API - for which we don't have any plans yet either.
However, we'd love to see a pull request on any of our repositories to improve the situation!
