### ISSUE TITLE
Can't find clear list of features

### ISSUE THREAD

**Issue by lelutin** [zammad/zammad-documentation#86]
Hello!

I was looking through the website on zammad.org, and documentation on docs.zammad.org and I couldn't find a clear list of features for what zammad supports.

For exemple, it supports interaction via email I suppose.. is it possible to integrate any other comms system with it? Is there some way to easily classify requests like queues (similar to RT) or tags or some other method? ... and there's probably so much more.

it would be great to see such a list of features on the website and in the docs.

**Comment by MrGeneration** [comment]
I'll mark this as "help wanted" for now as we're currently quite busy.

To your questions:
I think a close to complete "list" can be found within the the doctree of the documentation for admins: https://admin-docs.zammad.org/en/latest/

This lists nearly every feature Zammad does have (and explains it).
Beside that the API documentation ( https://docs.zammad.org/en/latest/api-intro.html ) and CTI API ( https://docs.zammad.org/en/latest/cti-api-intro.html ) might be interesting for you.

**Comment by MrGeneration** [comment]
I'll be closing this issue because of lacking feedback and PRs.
By now the commercial website of Zammad does have a pretty decent feature list available:

https://zammad.com/en/product/features

I personally think that this should be enough and isn't directly needed within a documentation.
Our three documentations cover nearly all Zammad functions and help to get a rough idea, however, they're not a PR page.
